### ISSUE TITLE
No error on conflicting plural messages

### ISSUE THREAD

**Issue by kevinschweikert** [elixir-gettext/gettext#400]
Hi,

i dont't know if this is really a `gettext` issue but when we cache the `_build` folder in our GitlLab CI Pipeline the command `mix gettext.extract --check-up-to-date` although it runs perfectly fine locally.
I suspect some `mtime` issues because the cache is restored after the repo is cloned. 

Any ideas on how to prevent this?

<details>
<summary>The Job definition</summary>

```yaml
locales:
  stage: lint
  image: $ELIXIR_IMAGE
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - _build
    - key:
        files:
          - mix.lock
      paths:
        - deps
  before_script:
    - apk add --no-cache make gcc libc-dev git
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
  script:
    - mix gettext.extract --check-up-to-date
  interruptible: true
  allow_failure: true
```

</details>
